# Generated by Django 4.1.7 on 2023-04-01 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djforms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='lasttname',
            new_name='lastname',
        ),
    ]
