# Generated by Django 4.1.7 on 2023-04-01 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djforms', '0002_rename_lasttname_candidate_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='age',
            field=models.CharField(default=datetime.datetime(2023, 4, 1, 20, 52, 37, 437656, tzinfo=datetime.timezone.utc), max_length=3),
            preserve_default=False,
        ),
    ]
