# Generated by Django 4.1.7 on 2023-04-03 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djforms', '0003_candidate_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.CharField(default=datetime.datetime(2023, 4, 3, 10, 31, 3, 195084, tzinfo=datetime.timezone.utc), max_length=17),
            preserve_default=False,
        ),
    ]
