# Generated by Django 4.1.7 on 2023-04-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djforms', '0004_candidate_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
