# Generated by Django 4.1.7 on 2023-04-03 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djforms', '0005_alter_candidate_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='job',
            field=models.CharField(default=datetime.datetime(2023, 4, 3, 11, 8, 1, 819862, tzinfo=datetime.timezone.utc), max_length=5),
            preserve_default=False,
        ),
    ]
