# Generated by Django 4.1.3 on 2023-02-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=3)),
                ('email', models.EmailField(max_length=50)),
                ('gender', models.CharField(choices=[('', 'Gender'), ('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=25)),
                ('request', models.CharField(choices=[('', 'Please Select Case Category'), ('Tax Matters', 'Tax Matters'), ('Employment', 'Employment'), ('Business Transaction', 'Business Transaction'), ('Debt Recovery', 'Debt Recovery'), ('Civil Matters', 'Civil Matters'), ('Child Custody', 'Child Custody'), ('Property', 'Property'), ('Disput', 'Disput'), ('Immigration', 'Immigration')], max_length=100, null=True)),
                ('description', models.TextField()),
                ('reg_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
