# Generated by Django 4.1.3 on 2023-02-09 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='reg_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='description',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='client',
            name='request',
        ),
        migrations.RemoveField(
            model_name='client',
            name='state',
        ),
        migrations.AddField(
            model_name='client',
            name='job',
            field=models.CharField(default=datetime.datetime(2023, 2, 9, 10, 9, 11, 968749, tzinfo=datetime.timezone.utc), max_length=5),
            preserve_default=False,
        ),
    ]
