# Generated by Django 4.1.3 on 2023-02-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_reg_at_client_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Situation',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='pending', max_length=50, null=True),
        ),
    ]
