# Generated by Django 4.1.3 on 2023-02-09 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_client_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='experience',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(default=datetime.datetime(2023, 2, 9, 20, 4, 58, 31192, tzinfo=datetime.timezone.utc), max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='personality',
            field=models.CharField(choices=[('', 'Select a Personality'), ('I am Outgoing', 'I am Outgoing'), ('I am Sociable', 'I am Sociable'), ('I am antisocial', 'I am antisocial'), ('I am discret', ' am discret'), ('I am serious', 'I am serious')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='salary',
            field=models.CharField(default=datetime.datetime(2023, 2, 9, 20, 5, 4, 542511, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='smoker',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'NO')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='Situation',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Pending', max_length=50, null=True),
        ),
    ]
